### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Rosenblack** [Reoseah/tree-hollows#6]
[log.txt](https://github.com/Reoseah/tree-hollows/files/8536195/log.txt)
it seems to have issues when loaded with the mods ive got listed in the log, without tree hollows loaded, it works fine but id like to use this mod so yeah

mc 1.18.2
fabric 0.14.0
fabric api 0.51.1

**Comment by reoseah** [comment]
Oh, it seems it's my code for compatibility with Architect's Palette breaks here. I'll look into it when I'll have time and energy

**Comment by reoseah** [comment]
Should be fixed in 1.3.3 (at https://www.curseforge.com/minecraft/mc-mods/tree-hollows/files/3770045 once it's approved)
