### ISSUE TITLE
game crashes when trying to create a new world

### ISSUE THREAD

**Issue by Immortal-Wolfie** [Reoseah/tree-hollows#8]
[crash-2022-04-24_21.07.34-client.txt](https://github.com/Reoseah/tree-hollows/files/8549542/crash-2022-04-24_21.07.34-client.txt)

**Comment by reoseah** [comment]
Duplicates https://github.com/Reoseah/tree-hollows/issues/6

**Comment by reoseah** [comment]
Should be fixed in 1.3.3 (at https://www.curseforge.com/minecraft/mc-mods/tree-hollows/files/3770045 once it's approved)
